name: Vitest Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unit_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm test
  # e2e:
  #   timeout-minutes: 60
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: lts/*
  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps

  #     # Zbudowanie aplikacji
  #     - name: Build application
  #       run: npm run build

  #      # Zwolnienie portu 5173, jeśli jest używany
  #      - name: Free port 5173 if in use
  #        run: kill $(lsof -t -i:5173) || true

  #      # Uruchomienie serwera Vite z logami
  #      - name: Start Vite server
  #        run: npm run preview &> vite.log &

  #      # Sprawdzenie dostępności serwera
  #      - name: Wait for Vite server
  #        run: npx wait-on http://localhost:5173 --timeout 200000

  #     # Potwierdzenie, że serwer działa, poprzez wykonanie zapytania HTTP
  #      - name: Confirm Vite server is running
  #        run: curl -I http://localhost:5173 || exit 1

  #      # Uruchomienie testów Playwright z verbose loggingiem i trace
  #      - name: Run Playwright tests with verbose logging
  #        env:
  #          DEBUG: pw:api
  #        run: npx playwright test --trace on

  #      # Pobranie logów serwera Vite dla diagnostyki
  #      - name: Check Vite server logs
  #        run: cat vite.log || true

  #      # Pobranie raportu Playwright
  #      - uses: actions/upload-artifact@v4
  #        if: always()
  #        with:
  #          name: playwright-report
  #          path: playwright-report/
  #          retention-days: 30

  #      # Pobranie trace z Playwright dla analizy
  #      - uses: actions/upload-artifact@v4
  #        if: always()
  #        with:
  #          name: playwright-trace
  #          path: test-results/*.zip
